version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:13.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=playground
    ports:
      - "5432:5432"