# Generated by Django 4.2.4 on 2023-08-22 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("post", "0002_like"),
    ]

    sql = """create table post_scrap
(
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    post_id    bigint                   not null,
    user_id    bigint                   not null,
    primary key (post_id, user_id)
);"""

    operations = [
        migrations.RunSQL(sql),
    ]
